name: CI/CD - pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        working-directory: ./simply_deploy
        run: dotnet restore 

      - name: Build the solution
        working-directory: ./simply_deploy
        run: dotnet build --configuration Release --no-restore

      - name: Run unit test
        working-directory: ./simply_deploy
        run: dotnet test --configuration Release --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        working-directory: ./simply_deploy
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./BettingApi.Test/TestResults/TestResults.trx