name: CI/CD - pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        working-directory: ./simply_deploy
        run: dotnet restore 

      - name: Build the solution
        working-directory: ./simply_deploy
        run: dotnet build --configuration Release --no-restore

      - name: Run unit test
        working-directory: ./simply_deploy
        run: dotnet test --configuration Release 


      - name: Publish
        working-directory: ./simply_deploy/BettingApi
        run: dotnet publish -c Release --self-contained -r win-x86

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./simply_deploy/BettingApi/bin/Release/net9.0/win-x86/publish/   # <-- update to your publish path
          server-dir: /public_html/    # same as your hosting provider
          # dangerous-clean-slate: false # <-- IMPORTANT! prevents deleting everything
          # exclude: |
          #   .well-known/**            

          # port: 21                    
          # protocol: ftp                